.travis.yml, docs/README.md
Travis now takes care of building the HTML version of the spec and
uploading it to AWS S3. This works for every branch that is hosted on
the p4lang/p4runtime repo, but not for PRs opened from forks (for
security reasons).
=> Add Travis CI

docs/README.md, docs/v1/P4Runtime-Spec.mdk, docs/v1/cpp.json, docs/v1/proto.json, docs/v1/prototext.json
We do not use P4 as the default language for every code block. We now
have extra syntax files for .proto, .cpp and .pb.txt. The C++ syntax
highlighter was taken from the Madoko github. There is probably a lot of
room for improvement for the proto ones.
I added an FAQ to the docs' README to keep track of some Madoko
"specificities".
=> Improve syntax highlighting for code blocks

.travis.yml, CI/Dockerfile, CI/compile_protos.sh, README.md, docs/README.md
Run protoc on the P4Runtime Protobuf files to ensure they are still
correct in case they are modified by a PR.
=> Validate Protobuf files as part of CI

README.md, docs/README.md, docs/v1/P4Runtime-Spec.mdk, docs/v1/README.md
I have given-up on fixing the tables in the generated PDF. It may be
possible by injecting some Tex directly in the Madoko source file, but
it sounds tedious and hard to maintain. So instead, I have cleaned-up
the tables that could be cleaned-up easily (i.e. these that don't have
long lines of text) using the Madoko online editor, and I have replaced
all other tables with lists. I did prefer the tables (in HTML) but the
lists do look okay IMO and they should be easier to modify & maintain.
Fixes #12
=> Clean-up tables in specification

docs/v1/P4Runtime-Spec.mdk, proto/p4/config/v1/p4info.proto, proto/p4/v1/p4runtime.proto
* use list for references
* change size and placement for figures
* use backticks for `@id` and `@controller_header` in mdk file to avoid warnings
* fix typo in proto comments
See individual commit messages for more details.
=> Minor fixes in spec

docs/README.md, docs/v1/P4Runtime-Spec.mdk, docs/v1/README.md, docs/v1/p4.json
I made sure that the formatting was somewhat uniform across the whole
document and I added backticks for inline code. I updated the README to
include some of the rules (arbitrary?) I tried to follow.
Fixes #26
=> Spec-wide review and formatting uniformization

docs/README.md, docs/v1/P4Runtime-Spec.mdk, docs/v1/README.md, docs/v1/bibref_no_title.js, docs/v1/references.bib
Madoko uses BibTeX for bibliography which supports online / web
references. We move all the references to a .bib file and include it in
the Madoko source. The end-result looks very nice and references will
definitely be easier to maintain this way.
It seems that dvipng is used to render "math" inside BibTex strings (we
need it to render P4_16 in subscript notation). For people building
locally, dvipng will need to be installed.
Fixes #25
=> Use Madoko bibliography support for references

BAZEL_NOTES.md, BUILD, WORKSPACE, bazel/BUILD, bazel/deps.bzl, bazel/external/BUILD, bazel/external/googleapis.BUILD, bazel/rules.bzl, bazel/workspace_rule.bzl, proto/README.md
An attempt at #4
We import rules to invoke protoc from pubref/rules_protobuf. The
alternatives would have been 1) try to use native Bazel rules only and
rules from the gRPC reprository, or 2) invoke protoc directly in the
BUILD file.
1) is an issue because of multiple issues with the native & gRPC rules.
2) may actually be the best solution, in terms of usability and
compatibility with different versions of protobuf, gRPC and Bazel.
See BAZEL_NOTES.md for a more comprehensive discussion.
=> Attempt at adding Bazel rules for protos

BUILD, bazel/external/googleapis.BUILD, proto/README.md
We use the following convention:
* `foo_[lang]_proto` for proto libraries
* `foo_[lang]_grpc` for proto libraries with gRPC support
We also add code_cc_proto target.
=> Rename Bazel proto rules

docs/v1/P4Runtime-Spec.mdk, docs/v1/references.bib, proto/p4/config/v1/p4info.proto, proto/p4/config/v1/p4types.proto
We update P4DataTypeSpec to be able to represent user-defined types in
P4Info. Translation (when the control-plane view differes from the
underlying data-plane type) may be required for new types through the
@p4runtime_translation annotation and this information is preserved in
P4Info. As decided previously, we do not break backward-compatibility
for action parameters and match fields. For these we do not use
P4DataTypeSpec but instead we add a new Protobuf field ("type_name")
which is set if the action parameter / match field is a user-defined
type (which must map to an underlying bit vector in this case).
=> Tentative support for new (user-defined) types in P4Info

docs/v1/P4Runtime-Spec.mdk, proto/p4/v1/p4runtime.proto
Also fixed the Protobuf type for some standard (translated) PSA metadata
entities, such as multicast group id. The Protobuf type is determined by
the bitwidth of the translated type. It is somewhat independent of the
corresponding PSA InHeader_t types.
Fixes #49
Fixes #51
=> Add reserved SDN port numbers to P4Runtime

.travis.yml, docs/v1/P4Runtime-Spec.mdk, docs/v1/references.bib, proto/p4/config/v1/p4info.proto
There doesn't seem to be any point in keeping this in P4Info at the
moment. First the semantics are murky because in PSA each execute call
on a meter is either color-aware or color-blind (i.e. it is not an
attribute of the meter object itself). Second, at the moment this
information cannot be leveraged in any way by a P4 client since
P4Runtime does not expose any knob to enable / disable color-awareness
on a per meter entry basis at runtime. Even if there was such a knob, it
would be hard to reconciliate it with PSA semantics: in PSA the same
meter can be "executed" in 2 different actions, in color-aware mode in
one and in color-blind mode in the other; these 2 action can use the
same indirect meter entry.
Fixes #58
=> Remove meter color-awareness information from P4Info

docs/v1/P4Runtime-Spec.mdk
If no config was previosuly set, server should return NOT_FOUND.  I was
tempted to use FAILED_PRECONDITION instead but it seems that NOT_FOUND
is preferred:
https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto
=> Minor error code adjustment for invalid COMMIT action

proto/p4/v1/p4runtime.proto
Some comments for direct resource fields in TableEntry did not match the
spec. Other comments needed some formatting work.
=> Fix comments in p4runtime.proto

docs/v1/P4Runtime-Spec.mdk, proto/p4/v1/p4data.proto
In order to facilitate read-write symmetry. If we only have one valid
representation, it needs to be the bitvector one, as not all possible
numeric values have to be named.
Fixes #64
=> Move to canonical representation for serializable enums

docs/v1/P4Runtime-Spec.mdk
No one volunteered for this section and it does not seem strictly
required, so we are dropping it for now.
=> Drop "Lifetime of a Session" section from spec for v1.0.0

docs/v1/P4Runtime-Spec.mdk, docs/v1/references.bib
Mostly a pointer to the PSA specification, with some concrete examples
of the guarantees provided by the @atomic annotation with respect to
control-plane operations. Future versions of the PSA specification may
benefit from including more details about how the @atomic annotation
interacts with control-plane operations.
Fixes #54
=> Add section giving atomicity requirements for individual operations

docs/v1/P4Runtime-Spec.mdk, docs/v1/references.bib
Also remove an ambiguous sentence in the cloning section for which I
could find no corresponding text in the PSA 1.1.0 spec.
Fixes #82
=> Reference PSA 1.1.0 instead of the draft

README.md, docs/v1/P4Runtime-Spec.mdk, proto/p4/config/v1/p4info.proto, proto/p4/v1/p4runtime.proto
Includes also minor editorial changes:
- Consistently use "control plane" and "data plane"
- 80 chars column wrap
=> Typo fixes

docs/v1/P4Runtime-Spec.mdk
Including:
Mention that when a write batch completes, operations that return
error status are not committed to the data plane.
Allow `ROLLBACK_ON_ERROR` batch write requests to be implemented by
servers for some batch operations, but not others, similar to how this
is specified for `DATAPLANE_ATOMIC` write requests.
=> Various small proposed improvements

docs/v1/P4Runtime-Spec.mdk
Remove UNSPECIFIED enum value for idle timeout.
Fixes #108
Clarify wording of P4DataTypeSpec description.
Fixes #112
Describe ambiguous read case when the table includes a "don't care"
entry.
Fixes #115
Use weaker wording for notification generation (idle timeout & digest),
in case the server is flooded with notifications from the data plane.
Fixes #116
Fix one-shot action profile programming: use valid ids and re-order
messages for traditional equivalent message sequence.
=> Misc fixes in the P4Runtime spec

docs/v1/P4Runtime-Spec.mdk
+ To FieldMatch and action Param, add controller packet metadata,
which has the same restriction as the other two.
+ Tighten the restriction to only unsigned bitstrings, i.e. values of
type bit<W>.  The P4Info file has only a bitwidth value to describe
the types of these values, with no way to distinguish int<W> from
bit<W>.
=> Update one of the known limitations bullet items

docs/v1/P4Runtime-Spec.mdk, proto/p4/v1/p4data.proto
By introducing additional constraints, thus ensuring read-write
symmetry.
Fixes #141
=> Define canonical representation for P4Data compound types

docs/v1/P4Runtime-Spec.mdk
In this case, I think both solutions (use the last occurrence or reject
the program) are valid. However, the current p4c complier rejects the P4
program in case of duplicate keys. Since it is "hard" to change the
implementation (the error happens when instantiating the IR, not when
generating the P4Info), I suggest we just match the current
implementation...
=> Match the p4c implementation for duplicate keys in PkgInfo

docs/v1/P4Runtime-Spec.mdk
I don't see a use case for this and this would potentially make
P4Runtime implementation trickier.
=> Add to the spec that idle timeout for default entries is not supported

docs/v1/P4Runtime-Spec.mdk, proto/p4/v1/p4runtime.proto
I think it makes sense to include that information for the P4Runtime
client.
=> Require idle_timeout_ns to be set in IdleTimeoutNotification

docs/v1/P4Runtime-Spec.mdk, proto/p4/config/v1/p4info.proto
This is done in a similar fashion to other kinds of translation (e.g. for match
fields). It is convenient to support translation for indices as it is not
unusual for indirect counters or registers to be indexed by the ig / eg port.
Fixes #131
=> Support numeric translation for counter / meter / register indices

docs/README.md, docs/v1/P4Runtime-Spec.mdk, proto/p4/v1/p4runtime.proto
* Use lowercase letters consistently in the protos and spec. This is an
arbitrary decision for the sake of uniformity. It seems that
lowercase letters were already used in most places.
* Add missing backticks for one occurrence of TableEntry
People may start thinking I'm running out of things to do.
=> Formatting nitpicks

docs/README.md, docs/v1/P4Runtime-Spec.mdk
Using - can cause issues in list formatting. While browsing the spec, I
found one such issue, which triggered this change.
=> Use --- for em dash in spec, not -

docs/v1/P4Runtime-Spec.mdk
* State that the device configuration needs to be securely transferred to the controller
* Mention that the controller should authenticate the switch device_id during the handshake
* could->should for gRPC authentication
Looks like Andy Fingerhunt already mentioned the need for gRPC authentication, which is great, however, I've changed could -> should to make it stronger.
=> Security concerns for the P4Runtime handshake

docs/v1/P4Runtime-Spec.mdk
Large batches in the `Write` RPC can cause gRPC to error with `RESOURCE_EXHAUSTED`, because the default maximum size for metadata is very low.  This new section shows how to avoid that.
=> Appendix with implementation advice for avoiding common pitfalls

docs/v1/P4Runtime-Spec.mdk, proto/p4/config/v1/p4info.proto
Add a description of this field to the text of the section describing
the contents of ControllerPacketMetadata messages.
Also add a description of the type_name field in the ValueSet section.
It was already re-using the MatchField messages used by table search
key fields, and already had this type_name field in it, but it seems
best to explicitly mention that it can be included in MatchField
messages for ValueSet objects, too.
=> Add type_name field to P4Info Metadata message

docs/v1/P4Runtime-Spec.mdk
... on type declarations in a P4 program.
Fixes #195
=> Document that p4runtime_translation annotations need only be supported

docs/v1/P4Runtime-Spec.mdk, proto/p4/v1/p4runtime.proto
This field may be used by the server to report errors generated by
invalid / unauthorized StreamMessageRequests.
Fixes #215
=> Add error field to StreamMessageResponse oneof

docs/v1/P4Runtime-Spec.mdk, proto/p4/v1/p4runtime.proto
For consistency with the rest of the P4Runtime API, a wildcard Read is
achieved by "setting" the `multicast_group_id` (resp. `session_id`)
field to its default value, which is 0 for sclar fields.
This means that we introduce a small difference with the PSA spec, which
explicitly allows 0 for clone session ids.
=> Support wildcard reads for multicast groups and clone sessions

.travis.yml, docs/v1/P4Runtime-Spec.mdk, tools/madokolint.py
It is quite a primitive tool at the moment but it makes sure that:
* there is no trailing whitespace
* lines longer than 80 chars are wrapped
* `&eg;` and `&ie;` are used
=> Add linter for P4Runtime Madoko spec

docs/v1/P4Runtime-Spec.mdk, docs/v1/references.bib
As was decided at the 07/31/2019 API WG meeting.
This commit also fixes an anchor issue caused by 2 different sections
being named "Wildcard Reads".
Fixes #237
=> Call out that reading entire state with empty entity is not supported

docs/v1/P4Runtime-Spec.mdk
Fixes #245.
Note that I also reworded/shortened some of the "advisory" text.  I think I preserved what we wanted to say before, but removed things I don't think we ever intended to say, and removed things that sounded overly prescriptive.  For instance, before we had a sentence:
> In other words, the client must wait until the dependent Write RPC is acknowledged before invoking a Write RPC that depends on it.
I don't think a client *must* do that.  It's certainly _advisable_ if the client wants deterministic (and useful) behavior from the switch, but they are not *required* to do that.  That's an important distinction.
=> Clarify ordering requirements.

docs/v1/P4Runtime-Spec.mdk, proto/p4/v1/p4runtime.proto
The P4Runtime API WG decided to include this to P4Runtime v1.1. For now,
this RPC will only enable the client to query the version of the
P4Runtime specification implemented by the server.
Fixes #249
=> Add Capabilities RPC to P4Runtime service

docs/v1/references.bib
References to xform where removed from the spec after support for
"documentation" annotations was added to the standard p4c compiler. It
seems that we forgot to remove the "xform" entry from the bibliography
at the time.
=> Remove reference to xform from bibliography

CI/deploy.sh
This makes it clear when the spec was last updated when looking at gh-pages.
=> Update commit author date when deploying spec

docs/v1/P4Runtime-Spec.mdk
This updates section 12.1 (Batching and Ordering of Updates) to match
the stronger guarantees in section 13.4 (Parallelism of Read and Write
Requests).
Fixes #258
=> Fix inconsistency in spec regarding Write consistency guarantees

docs/v1/P4Runtime-Spec.mdk, proto/p4/config/v1/p4info.proto, proto/p4/v1/p4runtime.proto
`optional` is a new match kind that matches either exactly, or is a wildcard.  Note that unlike `ternary`, there is no mask, it is either a full match on all bits, or a complete wildcard.  This was proposed to be added to the language, and in the LDWG meeting from Jan 6, 2020, we decided the newly proposed match kind  should be added to v1model and P4RT first, and possibly later consider promoting it to the `core.p4` standard library.  This PR is to add it to P4RT, and https://github.com/p4lang/p4c/pull/2141 will add support to v1model.
More details on the original discussion in the LDWG meeting notes and here: https://github.com/p4lang/p4-spec/issues/794.
=> Support for new optional match kind

docs/v1/P4Runtime-Spec.mdk, docs/v1/references.bib
To indicate that this is an unreleased version of P4Runtime, and avoid
confusion.
=> Update P4Runtime version to 1.2.0-dev

docs/v1/P4Runtime-Spec.mdk
This is as proposed in #268, but also adding it for packetio headers, which seems natural.
=> Add the ability to use @id for action params, table keys and packetio headers

docs/v1/P4Runtime-Spec.mdk, docs/v1/references.bib, proto/p4/config/v1/p4info.proto, proto/p4/config/v1/p4types.proto, proto/p4/v1/p4runtime.proto
This PR updates p4info.proto and p4types.proto as well as the P4Runtime specification to add structured annotations as described in https://github.com/p4lang/p4runtime/issues/264 and https://github.com/p4lang/p4-spec/pull/796. The P4_16 lang spec PR is not yet ratified, it is awaiting a practical implementation in `p4c` so one goal of this PR is to inform an implementation. Step one is to parse the syntax, step two is to generate the new `P4info`.
=> Added Structured Annotations

docs/v1/P4Runtime-Spec.mdk
https://github.com/p4lang/p4runtime/pull/272 added support for table
match fields, action parameters, and controller header metadata, but we
forgot value_set match fields, as pointed out by @jafingerhut.
=> Support @id annotations for value_set match fields

docs/v1/P4Runtime-Spec.mdk
I believe that these are clarifications to the existing P4Runtime API
specification, not changes to its behavior.
=> Clarifications on action profiles and selectors

docs/v1/P4Runtime-Spec.mdk, proto/p4/config/v1/p4info.proto, proto/p4/config/v1/p4types.proto
While working on the p4c implementation, I realized that:
* the ActionRef message was missing a structured_annotations field
* we use kvpair and kv_pair inconsistently
=> Small fixes for structured annotations

docs/v1/P4Runtime-Spec.mdk
Order is flipped: https://p4.org/p4-spec/docs/P4-16-v1.1.0-spec.html#sec-newtype
=> Fix P4 example about port number translation

docs/v1/P4Runtime-Spec.mdk, docs/v1/guidance-for-generating-p4info.md, docs/v1/p4runtime-id-notes.md, docs/v1/references.bib
Changes for P4Runtime release 1.2.0-rc.1
* Update version to 1.2.0-rc.1 for release
* Update references to P4_16 spec from 1.2.0 to 1.2.1
* Update companion documents
=> Changes for P4Runtime release 1.2.0-rc.1

bazel/example/WORKSPACE.bazel
The "bazel" branch no longer exists after merging #297. This is
temporary until tag v1.2.0 is available.
=> Fix Bazel example

README.md
There was a typo in the badge link, causing the bade not to display correctly.
=> fix badge in README

bazel/example/WORKSPACE.bazel, proto/WORKSPACE.bazel
We want `bazel/example` to accomplish two things:
* It should serve as a template for people who want to use p4runtime in their own Bazel project.
* It should ensure that the current master commit of p4runtime builds when included in third-party Bazel projects.
This PR fixes the second point. Before this PR, we would build a fixed commit rather than the latest commit.
=> CI should build latest commit, not latest release.

codegen/update_go.sh
-p isn't supported on Mac, but a template can be provided be provided on Linux and Mac
=> Fix codegen/update_go.sh for Mac

.github/workflows/ci-build-proto.yml, proto/p4runtime_deps.bzl
Our CI uses the latest available version of Bazel, which is now 4.0.
With this new Bazel release, the build started breaking, which required
upgrading dependencies to the following versions:
* Protobuf: v3.13
* gRPC: v1.35
* googleapis: top-of-tree
* rules_proto: top-of-tree
We also start running the Github workflow as a CRON job to ensure that
we catch these failures early in the future (in this case, the failure
was detected because of the p4lang/PI Bazel CI build).
=> Update versions of dependencies for Bazel build

.github/workflows/ci-build-proto.yml
GitHub's caching mechanism never overwrites cache entries for existing keys. Since we were using a static key, this caused our cache to never be refreshed. With this PR, a new cache entry is generated whenever any Bazel files (including dependencies) change.
=> Improve CI build times through smarter caching

docs/v1/P4Runtime-Spec.mdk
This highlights the known limitation, and allows implementations to
avoid considering negative integers when forming canonical bytestrings
for table and action profile entities.
=> Clarify P4RT major version in Bytestrings section

.github/workflows/ci-build-proto.yml
There seems to be a Bazel issue which can be resolved by expunging the
cache: https://github.com/bazelbuild/bazel/issues/9213
=> Discard existing Bazel cache for Github build

docs/v1/P4Runtime-Spec.mdk
Since MODIFY allows for more specific error codes where applicable it seems like the intent may have been to allow INSERTS the same discretion?
=> Clarify that write interts can use more specific error codes.

proto/BUILD.bazel, proto/WORKSPACE.bazel
This PR adds go_proto_library rule for p4runtime.proto in BUILD file.
=> Add Go proto build rule for p4runtime

docs/v1/P4Runtime-Spec.mdk
=> Restrict max_group_size to be less than size in Action Selectors.

docs/v1/P4Runtime-Spec.mdk
See issue #361.
This text seems to have originally come from a large commit from two years ago fixing master arbitration updates: https://github.com/p4lang/p4runtime/commit/c3f6bdc3499910f4ba85c24215e7ba6fe579e414
=> Simplify semantics for "no-op" master arbitration updates

.github/workflows/tag-uploads.yml
The pypa/gh-action-pypi-publish action doesn't take care of building the
distribution.
See
https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/
=> Build Python distribution before pushing to PyPI

docs/v1/P4Runtime-Spec.mdk
Re-opening of #368 on a local branch.
See issue #365 for more details. I also made some minor language (and formatting?) improvements.
=> Update Master Arbitration Updates to clarify that (device_id, role, election_id) triples are only unique for live controllers.

proto/BUILD.bazel
This change will cause Bazel to automatically generate mocks for testing various interactions with gRPC calls.
The only semantic difference is the `generate_mocks = true`, the rest is automatic reordering by my auto-formatter :'(. 
We add and use this internally in Google, meaning that we can't open source some of our tests. I recently read that this should now be supported by Bazel.
=> Generate mocks for the C++ grpc library.

docs/v1/P4Runtime-Spec.mdk
@rhalstea and I were hoping that we could amend the specification to have some allowance for SDN ports that are not usable as watch ports. I don't know precisely what the concerns would be with this, so I figured I'd create a quick PR to get the discussion started.
Probably, we would, at least, want to add some information about what constitutes 'usable' in this context. I'm imagining that there would be some outside-of-P4RT notion of informing the controller which ports are valid for watch ports vs not (as I think is already the case for SDN ports in general?).
Should we discuss this in a meeting? Are there particular concerns related to having these two different types of SDN ports basically?
=> Allow for SDN ports that are not usable as watch ports.

README.md
The links in the current README point to versions last generated in 2021.  The ones in this PR were auto-generated on 2022-Oct-28 when I checked while creating this PR.
=> Update links to working draft in README

.github/workflows/ci-build-proto.yml, bazel/example/.bazelrc, bazel/example/WORKSPACE.bazel, proto/.bazelrc, proto/WORKSPACE.bazel, proto/p4runtime_deps.bzl
The build is currently failing on Ubuntu 22.04 (default Github CI runner) because of compilation warnings.
=> Update Protobuf and gRPC for Bazel build

docs/v1/P4Runtime-Spec.mdk
The specification states that Bytestrings of length zero are not allowed. Clarify that there are no restrictions on the "maximum" length only, to avoid potential confusion.
Closes https://github.com/p4lang/p4runtime/issues/420
=> Update P4Runtime-Spec.mdk to clarify length restrictions on Bytestrings

docs/v1/P4Runtime-Spec.mdk
In particular with regards to translated types.
=> Clarify section on Packet I/O messages

.github/workflows/any-branch-uploads.yml
Change CI  workflow to skip publishing if PR spawned by dependabot
=> Fixes https://github.com/p4lang/p4runtime/issues/439

docs/v1/P4Runtime-Spec.mdk, docs/v1/README.md, docs/v1/references.bib
Update the link to the auto-generated versions of the P4Runtime specification on the P4.org web site.
Update the section "P4 Language Version Applicability" to version 1.2.4 of the P4_16 language specification, but list 3 known exceptions of features that have not been explicitly addressed yet.
=> Fix #434: Remove obsolete TODO section in README

docs/v1/P4Runtime-Spec.mdk
During 2023-Sep-08 P4.org API work group meeting, it was agreed that there are no changes required to the P4Runtime API specification to be compatible with these updates in the language spec.
=> Remove 4 P4 language spec compatibility issues from the list

docs/v1/P4Runtime-Spec.mdk
Add 'Otherwise' to clarify how `id` and `index` are used in wildcard read of counter and meter.
Close #478
=> Clarify wildcard read of counter and meter

proto/LICENSE
We're running into build issues due to the symlink and some interaction with zip files. Since the original LICENSE file last changed  6 years ago, I figure we might be OK with the duplication instead of the sym link?
Previous error:
```
/home/runner/.cache/bazel/_bazel_runner/edc9951cbd41acd2e30f113cd8beddfe/external/bazel_tools/tools/build_defs/repo/http.bzl:372:31: in <toplevel>
ERROR: An error occurred during the fetch of repository 'com_github_p4lang_p4runtime':
Traceback (most recent call last):
File "/home/runner/.cache/bazel/_bazel_runner/edc9951cbd41acd2e30f113cd8beddfe/external/bazel_tools/tools/build_defs/repo/http.bzl", line 132, column 45, in _http_archive_impl
download_info = ctx.download_and_extract(
Error in download_and_extract: java.io.IOException: Error extracting …
```
=> Remove license symlink to resolve build issues.

go/p4/config/v1/p4info.pb.go, go/p4/v1/p4runtime.pb.go, proto/p4/config/v1/p4info.proto, proto/p4/v1/p4runtime.proto
This adds to staged version-1.4.0-rc branch which will be merged to main when we're ready to declare a 1.4.0 tag.
- Added comments to proto files with "Added in v1.4.0" or "Deprecated in v1.4.0" as needed.
I used the following commands to create a temp working file to examine changes since tagged version 1.3.0:
```
git diff v1.3.0 HEAD proto/p4/config/v1/*.proto > v1.3.0_diff.txt
git diff v1.3.0 HEAD proto/p4/v1/*.proto >> v1.3.0_diff.txt
```
=> Add v1.4.0 comments to protobufs - fix https://github.com/p4lang/p4runtime/issues/487

docs/v1/references.bib
The reference for RFC 2697 was missing from the references.bib file.
=> Add reference for RFC2697 to bib

bazel/example/WORKSPACE.bazel, go/p4/config/v1/p4info.pb.go, go/p4/v1/p4runtime.pb.go, proto/p4/config/v1/p4info.proto, proto/p4/v1/p4runtime.proto, rust/src/p4.config.v1.rs, rust/src/p4.v1.rs
Merge accumulated 1.4.0 updates by consensus in WG mtg:
- Add missing comments "Added in 1.4.0" and "Deprecated in 1.4.0" to protobufs
- Update script bazel comments to reflect version 1.4.0
- Regenerate protobuf client code
=> Version 1.4.0 rc updates to bazel and protobuf comments

README.md, docs/v1/P4Runtime-Spec.mdk
Reviewed all commits since v1.3.0 and ensured every change was mentioned in the change log. Added some structure to categorize the changes.
=> Fix issue 491 - update changelog for 1.4.0 changes

docs/v1/P4Runtime-Spec.mdk
Add short note about v1.4.1 since we have to increment the tag, can't reuse v1.4.0.
=> Added changelog for 1.4.1.

.github/workflows/ci-build-proto.yml
@jafingerhut  https://github.com/p4lang/p4runtime/pull/512#issuecomment-2537572636
=> Temporarily pin Ubuntu CI version to 22.04, since 24.04 causes regression. 

.github/workflows/any-branch-uploads.yml, .github/workflows/main-branch-uploads.yml, .github/workflows/tag-uploads.yml, .gitignore, docs/v1/Makefile
Moved the folder from docs/v1/build to docs/v1 and separately copied the generated files.
@chrispsommers
=> Fixed CI configuration: adapted folder structure

.github/workflows/any-branch-uploads.yml, .github/workflows/main-branch-uploads.yml, .github/workflows/spec.yml, .github/workflows/tag-uploads.yml, .gitignore, docs/v1/Makefile
As pointed out by Antonin [here ](https://github.com/p4lang/p4runtime/pull/539#issuecomment-2628030281), the PR bringing back the build folder, where the `.pdf ` and ` .html `specs will be stored
=> Fix CI P4Runtime Spec

bazel/example/using-bzlmod/.bazelrc, bazel/example/using-workspace/.bazelrc, proto/.bazelrc
Update bazel build to c++17
c++17 has been out for awhile so this is a stable update.
c++17 is a prerequisite for migrating from proto3 to proto editions so would be nice to clear that prerequisite early
=> Update bazel build to c++17
