p4lang/p4runtime

.travis.yml, README.md, docs/README.md
Not just HTML version.
Fixes #16
=> Generate and upload PDF spec as part of Travis CI

docs/v1/P4Runtime-Spec.mdk, docs/v1/references.bib
With content from slides from last P4 Workshop.
Fixes #23
=> Update scope section

docs/v1/P4Runtime-Spec.mdk
=> Call out that role definition is out-of-scope of document

docs/v1/P4Runtime-Spec.mdk
I think these sentences should be part of the list item.
=> Minor formatting fixes.

docs/v1/P4Runtime-Spec.mdk
=> Clarify server behavior for malformed actions

docs/v1/P4Runtime-Spec.mdk, docs/v1/references.bib
This is a summary of the discussions we have had during various P4 API
Working Group meetings.
=> Add section on P4Runtime versioning

docs/v1/P4Runtime-Spec.mdk, proto/p4/v1/p4runtime.proto
With some information about what a role definition may include.
Fixes #56
=> Clarify controller role definition

docs/v1/P4Runtime-Spec.mdk, proto/p4/config/v1/p4info.proto, proto/p4/v1/p4runtime.proto
It is not an annotation any more the latest P4_16 version
=> The value_set size is provided as a constructor parameter

docs/v1/P4Runtime-Spec.mdk
In "Role Config" section.
I am usually pretty good with checking the generated files, so I'm
unsure how this one slipped through the cracks :/
=> Fix Madoko list formatting

docs/v1/P4Runtime-Spec.mdk, docs/v1/references.bib, proto/p4/v1/p4runtime.proto
=> Remove "complete" flag from ReadResponse message

docs/v1/P4Runtime-Spec.mdk, docs/v1/references.bib
Link will be updated after PSA 1.1 release.
=> Add link to PSA specification

docs/v1/P4Runtime-Spec.mdk
And the guarantees provided by P4_16 / P4Runtime. This is mostly a
pointer to the relevant section in the P4_16 spec.
=> Add paragraph about table size

docs/v1/references.bib
=> Reference P4_16 spec version 1.1.0 instead of draft

docs/v1/P4Runtime-Spec.mdk, docs/v1/references.bib
Based on the PSA spec.
Fixes #44
=> More details on valid values for multicast and clone session ids

docs/v1/P4Runtime-Spec.mdk
=> Editiorial pass on P4Runtime spec before 1.0.0 final release

docs/v1/P4Runtime-Spec.mdk, proto/p4/config/v1/p4info.proto, proto/p4/v1/p4runtime.proto
=> Clarify the meaning of the alias field in P4Info

docs/v1/P4Runtime-Spec.mdk
I replaced PR https://github.com/p4lang/p4runtime/pull/103 (from a private fork) with this one from a branch, after incorporating all review comments.
=> Described @brief, @description and @pkginfo annotations.

docs/v1/P4Runtime-Spec.mdk
=> Fix definition of Action message in Table Entry section

docs/v1/P4Runtime-Spec.mdk
=> Call out that 0 is an invalid weight for selector members

docs/v1/P4Runtime-Spec.mdk
=> Include more information about operations allowed on constant tables

docs/v1/P4Runtime-Spec.mdk
=> Clarify meaning of max_size and max_group_size

docs/v1/P4Runtime-Spec.mdk
All the issues for the 1.0.0 milestone have been resolved!
=> Update version number to 1.0.0 for final release

docs/v1/README.md
Just a few packages that I noticed were required on linux.
=> Add some missing packages to instructions.

docs/v1/P4Runtime-Spec.mdk
=> Server implementation guideline for max receive message size

docs/v1/P4Runtime-Spec.mdk
=> Explicitly list additional types supported as table search key fields

docs/v1/guidance-for-generating-p4info.md
This is intended to be a supplement to the P4Runtime v1.0
specification, with details and examples for things that might not be
clear from reading the specification.
=> Add "Guide for Generating P4Info message" document

docs/v1/P4Runtime-Spec.mdk
... when serving ReadRequest and WriteRequest messages.
=> Text describing the parallelism allowed in a P4Runtime server

.travis.yml, CI/deploy.sh, README.md, docs/README.md
In order to be uniform with other p4.org projects.
See #197
=> Deploy generated spec to Github pages

CONTRIBUTING.md, tools/madokolint.conf.json, tools/madokolint.py
Also add a check to the Madoko lint tool to make sure that a small
subset of "keywords" (can be expanded later) are highlighted with
backticks.
=> Add CONTRIBUTING.md file

docs/v1/P4Runtime-Spec.mdk
We include all the significant changes from v1.0 to v1.1. Changes are
loosely ordered by "importance", i.e. how likely they are to impact
users / client & server implementations.
Fixes #255
=> Add Revision History Appendix

docs/v1/P4Runtime-Spec.mdk, docs/v1/guidance-for-generating-p4info.md, docs/v1/references.bib
* Update references to P4_16 spec from 1.1.0 to 1.2.0
* Use 1.1 / 1.1.0 when referring to the current P4Runtime version
* Update version to 1.1.0-rc.1 for release
=> Prepare release 1.1.0-rc.1

docs/v1/P4Runtime-Spec.mdk
No update required to Revision History.
=> Update version to 1.1.0 for release

README.md
Zoom meetings, mailing list, Slack
=> Add Community section to README

docs/v1/P4Runtime-Spec.mdk, proto/p4/v1/p4runtime.proto
=> Add metadata bytes field

docs/v1/P4Runtime-Spec.mdk, proto/p4/config/v1/p4types.proto
=> Support translation to strings

docs/v1/P4Runtime-Spec.mdk
=> Updating spec to include IANA-assigned port: 9559

README.md, docs/v1/P4Runtime-Spec.mdk, go/p4/config/v1/p4info.pb.go, go/p4/config/v1/p4types.pb.go, proto/p4/config/v1/p4info.proto, proto/p4/config/v1/p4types.proto
=> Clarify spec: annotation locations are optional.

docs/v1/P4Runtime-Spec.mdk
Use consistent action_profile_id in example
=> Fix One Shot Action Selector Programming example

README.md
Hi,
just a quick fix to the links showing P4Runtime specs.
=> fixed P4Runtime specs links

.github/workflows/tag-uploads.yml
Tag name should use ref_name, not ref.
=> Fix tag-uploads workflow

docs/v1/P4Runtime-Spec.mdk
=> Correct cross-reference

.github/workflows/ci-build-proto.yml, .github/workflows/codegen.yml, .github/workflows/spec.yml
Adding dev branches to the workflows
=> Adding dev branches to workflows

docs/v1/P4Runtime-Spec.mdk
Fixed last part of https://github.com/p4lang/p4runtime/issues/480
=> Update P4Runtime version to 1.5.0-dev

.github/workflows/any-branch-uploads.yml, .github/workflows/main-branch-uploads.yml, .github/workflows/tag-uploads.yml
Removed the 'ls' build, the folder is no longer generated
@chrispsommers
=> Fix CI failing 
